export enum IRmqSeverName{
    PROFILE = "PROFILE_SERVICE",
    AUTH = "AUTH_SERVICE",
    GATEWAY = 'GATEWAY_SERVICE',
    MATCH_MAKING = "MATCH_MAKING",
    CHAT = "CHAT_SERVICE",
    MEDIA = "MEDIA_SERVICE",
    FRIEND = "FRIEND_SERVICE",
}
